# $FreeBSD: head/usr.sbin/bsdconfig/include/Makefile 241899 2012-10-22 18:01:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/include
FILES=		bsdconfig.hlp messages.subr usage.hlp

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
