# $FreeBSD: head/lib/clang/include/Makefile 243830 2012-12-03 19:24:08Z dim $

.PATH: ${.CURDIR}/../../../contrib/llvm/tools/clang/lib/Headers

INCSDIR=${INCLUDEDIR}/clang/3.2

INCS=	__wmmintrin_aes.h \
	__wmmintrin_pclmul.h \
	altivec.h \
	ammintrin.h \
	avx2intrin.h \
	avxintrin.h \
	bmi2intrin.h \
	bmiintrin.h \
	cpuid.h \
	emmintrin.h \
	f16cintrin.h \
	fma4intrin.h \
	fmaintrin.h \
	immintrin.h \
	lzcntintrin.h \
	mm3dnow.h \
	mm_malloc.h \
	mmintrin.h \
	module.map \
	nmmintrin.h \
	pmmintrin.h \
	popcntintrin.h \
	rtmintrin.h \
	smmintrin.h \
	tmmintrin.h \
	wmmintrin.h \
	x86intrin.h \
	xmmintrin.h \
	xopintrin.h

.include <bsd.prog.mk>
