# $FreeBSD: head/usr.sbin/bsdinstall/scripts/Makefile 245702 2013-01-21 01:01:32Z nwhitehorn $

SCRIPTS= auto adduser checksum config docsinstall hostname jail keymap \
	 mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 rootpass \
	 script services time umount wlanconfig
BINDIR= /usr/libexec/bsdinstall

NO_MAN=	true

.include <bsd.prog.mk>
