# $Id$
# $FreeBSD: head/usr.sbin/bluetooth/hcseriald/Makefile 140941 2005-01-28 16:08:11Z ru $

PROG=		hcseriald
MAN=		hcseriald.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
