# $FreeBSD: head/usr.sbin/bsdconfig/networking/include/Makefile 242117 2012-10-26 02:45:29Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking/include
FILES=		messages.subr tcp.hlp

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
