#!/bin/sh

. ~/.bashrc

export MOUNT_POINT=/mnt

cd ~/freebsd/freebsd

a="$( df | grep /mnt | wc -l )"

if [ $a \> 0 ];
then
	echo "Umounting /dev/da1p2..."
	sudo umount $MOUNT_POINT
	echo "Trying to mount again..."
	sudo mount /dev/da1p2 $MOUNT_POINT
else
	echo "Mounting..."
	sudo mount /dev/da1p2 $MOUNT_POINT
fi

echo "Installing world..."
sr make -j9 installworld > /tmp/log_install_world

echo "Installing kernel..."
sr make -j9 installkernel > /tmp/log_install_kernel

# update vm - not sure if necessary
echo "Update virtual machine with source..."
sr sh ~/freebsd/freebsd/vm_test_scripts/vmmake.sh -k /home/mm2260/freebsd/freebsd -x -c CADETS /mnt/mnt/test.img > /dev/null


