# $FreeBSD: head/lib/clang/libllvmlinker/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkArchives.cpp \
	LinkItems.cpp \
	LinkModules.cpp \
	Linker.cpp

.include "../clang.lib.mk"
