# $FreeBSD: head/lib/clang/libllvmlinker/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkModules.cpp \
	Linker.cpp

.include "../clang.lib.mk"
