# $FreeBSD: head/tools/tools/ath/athalq/Makefile 246935 2013-02-18 04:20:43Z adrian $

PROG=	athalq
NOMAN=	yes

SRCS=	main.c ar5210_ds.c ar5211_ds.c ar5212_ds.c ar5416_ds.c tdma.c
# SRCS+=	ar9300_ds.c

.include <../Makefile.inc>

.include <bsd.prog.mk>
