# $FreeBSD: head/tools/tools/ath/athalq/Makefile 243171 2012-11-17 02:37:25Z adrian $

PROG=	athalq
NOMAN=	yes

SRCS=	main.c ar5210_ds.c ar5211_ds.c ar5212_ds.c ar5416_ds.c
# SRCS+=	ar9300_ds.c

.include <../Makefile.inc>

.include <bsd.prog.mk>
