#!/bin/sh
#
# Add additional swap files
#
# $FreeBSD: head/etc/rc.d/addswap 240336 2012-09-11 05:04:59Z obrien $
#

# PROVIDE: addswap
# REQUIRE: FILESYSTEMS kld
# BEFORE:  netif
# KEYWORD: nojail

. /etc/rc.subr

name="addswap"
start_cmd="addswap_start"
stop_cmd=":"

addswap_start()
{
	case ${swapfile} in
	[Nn][Oo] | '')
		;;
	*)
		if [ -w "${swapfile}" ]; then
			echo "Adding ${swapfile} as additional swap"
			mdev=`mdconfig -a -t vnode -f ${swapfile}` && swapon /dev/${mdev}
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
