#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/bsnmpd 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bsnmpd"
rcvar="bsnmpd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/snmpd.pid"

load_rc_config $name
run_rc_command "$1"
