#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/sysctl 244198 2012-12-13 23:32:47Z delphij $
#

# PROVIDE: sysctl

. /etc/rc.subr

name="sysctl"
command="/sbin/sysctl"
stop_cmd=":"
start_cmd="sysctl_start"
reload_cmd="sysctl_start"
lastload_cmd="sysctl_start last"
extra_commands="reload lastload"

sysctl_start()
{
	case $1 in
	last)
		command_args="-i -f"
	;;
	*)
		command_args="-f"
	;;
	esac

	for _f in /etc/sysctl.conf /etc/sysctl.conf.local; do
		[ -r ${_f} ] && ${command} ${command_args} ${_f} > /dev/null
	done
}

load_rc_config $name
run_rc_command "$1"
