# $FreeBSD: head/lib/clang/libllvmobject/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmobject

SRCDIR=	lib/Object
SRCS=	Archive.cpp \
	Binary.cpp \
	COFFObjectFile.cpp \
	ELFObjectFile.cpp \
	Error.cpp \
	MachOObject.cpp \
	MachOObjectFile.cpp \
	Object.cpp \
	ObjectFile.cpp

.include "../clang.lib.mk"
