# $FreeBSD: head/lib/clang/libllvmvectorize/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmvectorize

SRCDIR=	lib/Transforms/Vectorize
SRCS=	BBVectorize.cpp \
	LoopVectorize.cpp \
	Vectorize.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
