# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: head/sbin/routed/rtquery/Makefile 228607 2011-12-16 23:43:58Z dim $

PROG=	rtquery
MAN=	rtquery.8
LDADD=	-lmd
DPADD=	${LIBMD}
WARNS?=	3
NO_WARRAY_BOUNDS=

.include <bsd.prog.mk>
