# $FreeBSD: head/lib/clang/libllvmmcdisassembler/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmmcdisassembler

SRCDIR=	lib/MC/MCDisassembler
SRCS=	Disassembler.cpp \
	EDDisassembler.cpp \
	EDInst.cpp \
	EDOperand.cpp \
	EDToken.cpp

.include "../clang.lib.mk"
