# $FreeBSD: head/lib/clang/libllvmmcjit/Makefile 243830 2012-12-03 19:24:08Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp

.include "../clang.lib.mk"
