# $Id$
# $FreeBSD: head/etc/bluetooth/Makefile 151325 2005-10-14 15:26:23Z ru $

FILESDIR=		/etc/bluetooth
FILES=			hcsecd.conf hosts protocols
FILESMODE_hcsecd.conf=	600
FILESMODE_hosts=	644

.include <bsd.prog.mk>
