# $FreeBSD: head/usr.sbin/bsdconfig/examples/Makefile 238438 2012-07-14 03:16:57Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
