#	$FreeBSD: head/tools/tools/ath/Makefile 244953 2013-01-02 04:02:27Z adrian $

SUBDIR=	arcode athdebug athdecode athkey athpoke athprom athrd athregs
SUBDIR+=	athstats ath_prom_read athradar athaggrstats
SUBDIR+=	ath_ee_v14_print ath_ee_v4k_print ath_ee_9287_print
SUBDIR+=	athsurvey athratestats athspectral

.include <bsd.subdir.mk>
