.\" Copyright (c) 2016 Robert N. M. Watson
.\" All rights reserved.
.\"
.\" This software was developed by BAE Systems, the University of Cambridge
.\" Computer Laboratory, and Memorial University under DARPA/AFRL contract
.\" FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent Computing
.\" (TC) research program.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd December 23, 2016
.Dt GETUUID 2
.Os
.Sh NAME
.Nm fgetuuid ,
.Nm getuuid ,
.Nm lgetuuid
.Nd system calls to retrieve UUIDs of files and file descriptors
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In sys/uuid.h
.In sys/metaio.h
.Ft int
.Fn fgetuuid "int fd" "struct uuid *uuidp"
.Ft int
.Fn getuuid "const char *path" "struct uuid *uuidp"
.Ft int
.Fn lgetuuid "const char *path" "struct uuid *uuidp"
.Sh DESCRIPTION
The
.Fn fgetuuid ,
.Fn getuuid ,
and
.Fn lgetuuid
system calls retrieve UUIDs associated with files and file descriptors, which
will be written to memory pointed to by the
.Va uuidp
argument.
The file to operate on is selected wth the file descriptor
.Fa fd
for
.Fn fgetuuid ,
or a
.Fa path
argument
for
.Fn getuuid
and
.Fn lgetuuid .
.Fn getuuid
follows a symlink in the final element of the path;
.Fn lgetuuid
does not.
.Pp
UUIDs on files uniquely identify the file regardless of its name and access
mechanism, although the means by which they are generated will be specific to
the filesystem or other kernel subsystem that generates them.
.Pp
Returned UUIDs can be processed and printed using
.Xr uuid 3 .
.Sh RETURN VALUES
.Rv -std
.Sh ERRORS
The
.Fn fgetuuid ,
.Fn getuuid ,
and
.Fn lgetuuid
system calls can fail with:
.Bl -tag -width Er
.It Bq Er EFAULT
The buffer pointed to by
.Fa uuidp
could not be written to.
.It Bq Er EBADF
The fd argument is not a valid open file descriptor.
.It Bq Er EFAULT
The pathname pointed to by
.Fa path
could not be read.
.It Bq Er ENAMETOOLONG
A component of either pathname exceeded 255 characters, or the entire length
of either path name exceeded 1023 characters.
.It Bq Er ENOENT
A component of the from path does not exist, or a path prefix of to does not
exist.
.It Bq Er EACCES
A component of either path prefix denies search permission.
.It Bq Er EOPNOTSUPP
The filesystem or other kernel subsystem implementing the file or file
descriptor does not support UUIDs.
.Sh SEE ALSO
.Xr getuuid 1 ,
.Xr uuid 3
.Sh AUTHORS
This software and this manual page were developed by BAE Systems, the
University of Cambridge Computer Laboratory, and Memorial University under
DARPA/AFRL contract
.Pq FA8650-15-C-7558
.Pq Do CADETS Dc ,
as part of the DARPA Transparent Computing (TC) research program.
