.\"-
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2021 Robert N. M. Watson
.\"
.\" This software was developed by the University of Cambridge Computer
.\" Laboratory.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd November 4, 2021
.Dt DTRACED 8
.Os
.Sh DTRACED
.Nm dtraced
.Nd DTrace hypervisor management daemon
.Sh SYNOPSIS
.Nm dtraced
.Fl OZdhmqv
.Op Fl D Ar directory
.Op Fl t Ar size
.Sh DESCRIPTION
.Nm
is a system daemon responsible for coordinating DTrace-based tracing across
virtualization hosts and guests.
This is required for hypervisor-based tracing where scripts execute in the
host kernel, but probes are instrumented and fire from some combination of the
host and guest kernels.
On the host,
.Nm
receives connections from local
.Xr dtrace 1
clients, loading DTrace scripts and distributing suitably linked versions of
scripts to all affected guests.
On the guest size,
.Nm receives DTrace scripts provided by the host and installs them so that
suitable guest probes fire.
.Nm
currently supports only the
.Xr bhyve 8
hypervisor.
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl D Ar directory
Specify the
.Nm
base directory, where scripts will be stored during excution.
The base directory defaults to
.Pa /var/ddtrace .
.It Fl O
Run
.Nm
in overlord mode, overriding automatic detection of being a hypervisor host.
.It Fl Z
Disable support for SHA256 hashing of all scripts.
Hashes are used when moving them between the host and guest, or on guest
reboot, to detect potential integrity issues.
This flag exists for debugging purposes only.
.It Fl d
Debug mode.
The server sends verbose debug output to standard error, and does not put
itself in the background.
.It Fl h
Print a help message and terminate.
.It Fl m
Run
.Nm
in minion mode, overriding automatic detection of being a hypervisor guest.
.It Fl q
Enable quiet mode, suppressing print of status updates and errors on the
terminal.
.It Fl v
Display version information.
.El
.Sh SEE ALSO
.Xr dtrace 1 ,
.Xr bhyve 8
.Rs
.%T Solaris Dynamic Tracing Guide
.Re
.Sh HISTORY
.Nm
was created as part of the DARPA CADETS project, a collaboration between BAE
Systems, the University of Cambridge, and Memorial University Newfoundland.
.Sh AUTHORS
.Nm
was created by
.An Domagoj Stolfa .
This manual page was written by
.An Robert Watson .
