# $FreeBSD: head/sys/modules/iwn/Makefile 243801 2012-12-02 22:18:01Z uqs $

.PATH:  ${.CURDIR}/../../dev/iwn

KMOD    = if_iwn
SRCS    = if_iwn.c device_if.h bus_if.h pci_if.h opt_wlan.h

.include <bsd.kmod.mk>
