#!/bin/sh

# PROVIDE: dtraced
# REQUIRE: DAEMON FILESYSTEMS

. /etc/rc.subr

name="dtraced"
desc="DTrace daemon that manages DTrace scripts across hosts."
rcvar="${name}_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_precmd="${name}_precmd"

sockfile="/var/ddtrace/sub.sock"

dtraced_precmd()
{
	case "$dtraced_type" in
	overlord)
		rc_flags="-O ${rc_flags}"
		;;
	minion)
		rc_flags="-m ${rc_flags}"
		;;
	*)
		;;
	esac
	return 0
}

load_rc_config $name
run_rc_command "$1"


