#!/bin/sh
#
#
# $FreeBSD$
#
# Start up for the Virtual DDTrace script reader daemon
#

# PROVIDE: vm_ddtrace_consumer
# REQURIE: syslogd
# BEFORE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="vm_ddtrace_consumer"
rcvar=${name}_enable

desc="VM DDTrace consumer daemon"

command="usr/sbin/${name}"


load_rc_config $name
run_rc_command "$1"