#!/bin/sh
#
# Copyright (c) 2015 George V. Neville-Neil
# All rights reserved.
#
# This software was developed by BAE Systems, the University of
# Cambridge Computer Laboratory, and Memorial University under
# DARPA/AFRL contract FA8650-15-C-7558 ("CADETS"), as part of
# the DARPA Transparent Computing (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# [id for your version control system, if any]
#
#
# supersnooper - a script to help us find out "who did what to whom and when?"
#
# The supersnooper script combines the functionality found in
# execsnoop, rwsnoop, opensnoop, soconnect, ipio.d, and other scipts
# in order to generate a single stream of events that can help us
# correlate various actions across the entire system using DTrace

# Command line and argument passing

DTRACE="/mnt/minion/exported/github/CADETS/freebsd/cddl/usr.sbin/dtrace/dtrace"

# The DTrace Bits
# /usr/sbin/dtrace -n '
$DTRACE -n '
#pragma D option oformat=xml
syscall::execve:return
{
}
syscall::*read:entry,
syscall::*write:entry
{
}
syscall::open:entry
{
}
'
