#!/bin/sh
# $Id$

. ./setup-vars

RESULT=`$DIALOG --extra-button --extra-label "Hold" --help-button --stdout --title "CALENDAR" "$@" --calendar "Please choose a date..." 0 0 7 7 1981`
retval=$?

. ./report-string
