#!/bin/sh
# $Id$
# example with extra- and help-buttons

. ./setup-vars

. ./setup-edit

cat << EOF > $input
EOF

$DIALOG --title "EDIT BOX" \
	--extra-button \
	--help-button \
	--fixed-font "$@" --editbox $input 0 0 2>$output
retval=$?

. ./report-edit
