#!/bin/sh
# $Id$

. ./setup-vars

FILE=$HOME
for n in .cshrc .profile .bashrc
do
	if test -f $HOME/$n ; then
		FILE=$HOME/$n
		break
	fi
done

RESULT=`$DIALOG --stdout --title "Please choose a file" "$@" --fselect $FILE 14 48`
retval=$?

. ./report-string
