#!/bin/sh
# $Id$

. ./setup-vars

. ./setup-tempfile

. ./setup-utf8

$DIALOG \
--title    `printf "\xe3\x81\x82\xe3\x81\x84\xe3\x81\x86\xe3\x81\x88\xe3\x81\x8a"` "$@" \
--inputbox `printf "\xe3\x81\x82\xe3\x81\x84\xe3\x81\x86\xe3\x81\x88\xe3\x81\x8a"` \
10 20 "Ｄ.Ｏ.Ｇ"	 2>$tempfile

retval=$?

. ./report-tempfile
