#!/bin/sh
# $Id$

. ./setup-vars

. ./setup-tempfile

. ./testdata-8bit

$DIALOG \
--title    `printf "$SAMPLE"` "$@" \
--inputbox `printf "$SAMPLE"` \
10 40 `printf "$SAMPLE"` 2>$tempfile

retval=$?

. ./report-tempfile
