#!/bin/sh
# $Id$

. ./setup-vars

. ./setup-tempfile

ls -1 >$tempfile
(
while true
do
read text
test -z "$text" && break
ls -ld "$text"
sleep 1
done <$tempfile
) |

$DIALOG --title "PROGRESS" "$@" --progressbox 20 70
