# $FreeBSD: head/lib/clang/libllvmbitreader/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitcodeReader.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
