# $FreeBSD: head/lib/clang/libclangedit/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	clangedit

SRCDIR=	tools/clang/lib/Edit
SRCS=	Commit.cpp \
	EditedSource.cpp \
	RewriteObjCFoundationAPI.cpp

TGHDRS=	AttrList \
	Attrs \
	CommentNodes \
	DeclNodes \
	StmtNodes \
	DiagnosticCommonKinds

.include "../clang.lib.mk"
